services:

  database:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: split_db
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d


  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 8080:8080
      
